modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Cursee-Development/Sleepy-Hollows/issues"
license = "MIT"

[[mods]]
modId = "sleepy_hollows"
version = "${version}"
displayName = "Sleepy Hollows"
authors = "Jason13Official, Satisfy, cph101dev"
credits = "MissLilitu, CR-055, Iri, WearyPines"
description = '''
Darkness falls, a boss to dread, armor strong - don’t lose your head!
'''
logoFile = "pack.png"

[[dependencies.sleepy_hollows]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sleepy_hollows]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sleepy_hollows]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sleepy_hollows]]
modId = "terrablender"
mandatory = true
versionRange = "[3.0.0,)"
ordering = "AFTER"
side = "BOTH"
